$basePath = "d:\cyberAiOllama-master\frontend\nextjs-dashboard\src"

$files = @(
    "$basePath\app\(dashboard)\cve\page.tsx",
    "$basePath\app\(dashboard)\sandbox\page.tsx",
    "$basePath\app\(dashboard)\incidents\page.tsx",
    "$basePath\app\(dashboard)\live-monitor\page.tsx",
    "$basePath\app\(dashboard)\parse-ai\page.tsx",
    "$basePath\app\(dashboard)\parse-ai-history\page.tsx",
    "$basePath\app\(dashboard)\playbooks\page.tsx",
    "$basePath\app\(dashboard)\threat-report\page.tsx",
    "$basePath\app\(dashboard)\ip-intel\page.tsx",
    "$basePath\components\IPAnalysisResults.tsx",
    "$basePath\components\SandboxReport.tsx",
    "$basePath\components\AlertChart.tsx",
    "$basePath\components\LiveTrafficChart.tsx"
)

foreach ($file in $files) {
    if (Test-Path $file) {
        $content = Get-Content $file -Raw -Encoding UTF8

        # Remove standalone {" "} lines generated by prettier which break table hydration
        # Match newline, any whitespace, {" "}, and any whitespace/newline
        $newContent = $content -replace '(?m)^\s*\{\s*"\s*"\s*\}\s*$', ''
        
        # Also remove {" "} right next to table tags just in case
        $newContent = $newContent -replace '\{\s*"\s*"\s*\}', ''

        if ($content -ne $newContent) {
            Set-Content $file -Value $newContent -Encoding UTF8 -NoNewline
            Write-Host "Fixed JSX spaces in: $file"
        }
    }
}
